# Generated by Django 5.1.4 on 2024-12-23 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_mobile_number', message='Mobile number must be exactly 10 digits.', regex='^\\d{10}$')], verbose_name='Mobile Number'),
        ),
    ]
