# Generated by Django 5.1.4 on 2024-12-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GiftVouchers', '0002_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='customer_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
