# Generated by Django 5.1.4 on 2025-02-13 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('veg', 'Veg Menu'), ('non_veg', 'Non-Veg Menu'), ('dessert', 'Desserts Menu'), ('beverage', 'Beverages Menu')], max_length=20, unique=True, verbose_name='Menu Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay Order ID')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay Payment ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Dish Name')),
                ('description', models.TextField(verbose_name='Dish Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price (₹)')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='Menu.menu')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Special Requests')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.dish', verbose_name='Dish')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.menu', verbose_name='Menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Menu.order')),
            ],
        ),
    ]
