# Generated by Django 5.1.4 on 2024-12-27 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Special Requests')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.dish', verbose_name='Dish')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.menu', verbose_name='Menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Menu.order')),
            ],
        ),
    ]
