# Generated by Django 5.1.4 on 2024-12-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_order_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_email',
            new_name='email',
        ),
    ]
